import {
  LucideProps,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Bell,
  BookOpen,
  Briefcase,
  Calendar,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Code,
  Copy,
  CreditCard,
  DollarSign,
  Download,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Folder,
  Github,
  Globe,
  Grid,
  Heart,
  Home,
  Image,
  Info,
  Instagram,
  Layers,
  Link,
  List,
  Loader,
  Loader2,
  Menu,
  MessageCircle,
  MessageSquare,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Plus,
  Radio,
  Repeat,
  Search,
  Send,
  Settings,
  Share,
  Shield,
  ShoppingCart,
  Smartphone,
  Star,
  Sun,
  Trash,
  Trash2,
  TrendingUp,
  Upload,
  User,
  Users,
  Video,
  Wallet,
  X,
  ZoomIn,
  ZoomOut,
  Mail,
  Lock,
  LogOut,
  LogIn,
  MapPin,
  Zap,
  Award,
  Building,
  Dribbble,
  Figma,
  Linkedin,
  Sparkles,
  Terminal,
  Twitter,
  Volume2,
  VolumeX,
  Watch,
  Wifi,
  YouTube,
  UserPlus,
  Ban,
  AlertTriangle,
  Hourglass,
  BarChart2,
  PieChart,
  LineChart,
  MoreVertical as Eye2,
  UnplugIcon,
  ShieldAlert,
  ShieldCheck,
  PenTool,
  Paintbrush,
  Palette,
  Droplet,
  Music,
  Headphones,
  Percent,
  Cpu,
  Keyboard,
  Mouse,
  Wrench,
  Hammer,
  Tool,
  Lightbulb,
  Flame,
  Rocket,
  Target,
  Crosshair,
  Trophy,
  Medal,
  BadgeCheck,
  Fingerprint,
  Scan,
  QrCode,
  Barcode,
  Ticket,
  ShoppingBag,
  Gift,
  Package2,
  Truck,
  Plane,
  Train,
  Car,
  Bike,
  Walk,
  Accessibility,
  Wheelchair,
  Languages,
  GraduationCap,
  AtSign,
  type LucideIcon,
} from 'lucide-react'

export type Icon = LucideIcon

export const Icons = {
  // Navigation
  home: Home,
  search: Search,
  menu: Menu,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,

  // Actions
  edit: Edit,
  delete: Trash,
  delete2: Trash2,
  trash: Trash,
  copy: Copy,
  share: Share,
  download: Download,
  upload: Upload,
  send: Send,
  plus: Plus,
  filter: Filter,
  refresh: Repeat,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,

  // User & Auth
  user: User,
  users: Users,
  userPlus: UserPlus,
  lock: Lock,
  logout: LogOut,
  login: LogIn,
  mail: Mail,

  // Content
  fileText: FileText,
  folder: Folder,
  image: Image,
  video: Video,
  code: Code,
  terminal: Terminal,

  // Commerce
  wallet: Wallet,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  shoppingCart: ShoppingCart,
  shoppingBag: ShoppingBag,
  briefcase: Briefcase,

  // UI
  alert: AlertCircle,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  check: CheckCircle,
  checkCircle: CheckCircle,
  x: X,
  xCircle: X,
  info: Info,
  star: Star,
  heart: Heart,
  bell: Bell,
  grid: Grid,
  list: List,
  layers: Layers,
  link: Link,
  externalLink: ExternalLink,
  radio: Radio,

  // Time & Date
  calendar: Calendar,
  clock: Clock,
  watch: Watch,
  hourglass: Hourglass,

  // Theme
  sun: Sun,
  moon: Moon,
  smartphone: Smartphone,

  // Communication
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,

  // Status indicators
  spinner: Loader2,
  loader: Loader,

  // Business
  trendingUp: TrendingUp,
  barChart: BarChart2,
  pieChart: PieChart,
  lineChart: LineChart,
  building: Building,
  award: Award,
  zap: Zap,
  sparkles: Sparkles,
  shield: Shield,
  shieldCheck: ShieldCheck,
  shieldAlert: ShieldAlert,

  // Social
  github: Github,
  twitter: Twitter,
  instagram: Instagram,
  linkedin: Linkedin,
  dribbble: Dribbble,
  youtube: YouTube,

  // Miscellaneous
  mapPin: MapPin,
  figma: Figma,
  globe: Globe,
  bookOpen: BookOpen,
  wifi: Wifi,
  volume2: Volume2,
  volumeX: VolumeX,
  eye: Eye,
  eyeOff: EyeOff,
  ban: Ban,
  atSign: AtSign,
  graduationCap: GraduationCap,

  // Additional icons for components
  briefcase: Briefcase,
  percent: Percent,
  cpu: Cpu,
  keyboard: Keyboard,
  mouse: Mouse,
  wrench: Wrench,
  hammer: Hammer,
  tool: Tool,
  lightbulb: Lightbulb,
  flame: Flame,
  rocket: Rocket,
  target: Target,
  crosshair: Crosshair,
  trophy: Trophy,
  medal: Medal,
  badgeCheck: BadgeCheck,
  fingerprint: Fingerprint,
  scan: Scan,
  qrCode: QrCode,
  barcode: Barcode,
  ticket: Ticket,
  gift: Gift,
  package2: Package2,
  truck: Truck,
  plane: Plane,
  train: Train,
  car: Car,
  bike: Bike,
  walk: Walk,
  accessibility: Accessibility,
  wheelchair: Wheelchair,
  languages: Languages,
  penTool: PenTool,
  paintbrush: Paintbrush,
  palette: Palette,
  droplet: Droplet,
  music: Music,
  headphones: Headphones,
}

export type IconName = keyof typeof Icons
