import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Bell,
  BookOpen,
  Briefcase,
  Calendar,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Code,
  Copy,
  CreditCard,
  DollarSign,
  Download,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Folder,
  Github,
  Globe,
  Grid,
  Heart,
  Home,
  Image,
  InboxIcon,
  Info,
  Instagram,
  Layers,
  Link,
  List,
  Loader,
  Menu,
  MessageCircle,
  MessageSquare,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Plus,
  Radio,
  Repeat,
  Search,
  Send,
  Settings,
  Share,
  Shield,
  ShoppingCart,
  Smartphone,
  Star,
  Sun,
  Trash,
  TrendingUp,
  Tv,
  Type,
  Upload,
  User,
  Users,
  Video,
  Wallet,
  X,
  ZoomIn,
  ZoomOut,
  Mail,
  Lock,
  LogOut,
  LogIn,
  MapPin,
  Zap,
  Award,
  BarChart3,
  Building,
  Coffee,
  Dribbble,
  Figma,
  Folder as FolderIcon,
  Linkedin,
  Loader2 as Spinner,
  Sparkles,
  Terminal,
  Trash2,
  Twitter,
  Unlock,
  Upload as UploadIcon,
  Volume,
  VolumeX,
  Wand2,
  Watch,
  Wifi,
  Wind,
  X as XIcon,
  XCircle,
  YouTube,
} from 'lucide-react'

export const Icons = {
  // Navigation
  home: Home,
  search: Search,
  menu: Menu,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,

  // Actions
  edit: Edit,
  delete: Trash,
  delete2: Trash2,
  trash: Trash,
  copy: Copy,
  share: Share,
  download: Download,
  upload: Upload,
  uploadIcon: UploadIcon,
  send: Send,
  plus: Plus,
  filter: Filter,
  refresh: Repeat,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,

  // User & Auth
  user: User,
  users: Users,
  mailbox: InboxIcon,
  lock: Lock,
  unlock: Unlock,
  logout: LogOut,
  login: LogIn,
  mail: Mail,

  // Content
  fileText: FileText,
  folder: Folder,
  folderIcon: FolderIcon,
  image: Image,
  video: Video,
  type: Type,
  code: Code,
  terminal: Terminal,

  // Commerce
  wallet: Wallet,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  shoppingCart: ShoppingCart,
  briefcase: Briefcase,

  // UI
  alert: AlertCircle,
  alertCircle: AlertCircle,
  check: CheckCircle,
  checkCircle: CheckCircle,
  x: X,
  xIcon: XIcon,
  xCircle: XCircle,
  info: Info,
  star: Star,
  heart: Heart,
  bell: Bell,
  grid: Grid,
  list: List,
  layers: Layers,
  link: Link,
  externalLink: ExternalLink,
  radio: Radio,

  // Time & Date
  calendar: Calendar,
  clock: Clock,
  watch: Watch,

  // Theme
  sun: Sun,
  moon: Moon,
  smartphone: Smartphone,
  tv: Tv,

  // Communication
  message: MessageCircle,
  messageSquare: MessageSquare,
  mail: Mail,

  // Status indicators
  spinner: Spinner,
  loader: Loader,

  // Business
  trending: TrendingUp,
  barChart: BarChart3,
  building: Building,
  award: Award,
  zap: Zap,
  sparkles: Sparkles,

  // Social
  github: Github,
  twitter: Twitter,
  instagram: Instagram,
  linkedin: Linkedin,
  dribbble: Dribbble,
  youtube: YouTube,

  // Miscellaneous
  mapPin: MapPin,
  coffee: Coffee,
  wand: Wand2,
  figma: Figma,
  globe: Globe,
  bookOpen: BookOpen,
  shield: Shield,
  wifi: Wifi,
  wind: Wind,
  volume: Volume,
  volumeX: VolumeX,
}

export type IconName = keyof typeof Icons
